version: '3.8'

# services:
#   angular:
#     hostname: localhost
#     # container_name: front-prepagas
#     build: front-prepagas
#     ports:
#       - "8080:80"
#   express:
#     build: server
#     ports: 
#       - "3000:3000"
#     links:
#       - database
#   database:
#     image: mongo
#     ports:
#       - "27017:27017"


services:
  database:
    image: "mongo"
  express_app:
    build: ./server
    ports:
      - "5000:5000"
    expose:
      - "5000"
    links:
      - database
  angular_app:
    build: ./front-prepagas
    ports:
      - 4300:80
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    links:
      - express_app
      - angular_app 
  
  
    