version: "3.8"

services:
  database:
    image: "mongo"
    container_name: database

  express_app:
    build: ./server
    container_name: express_app
    ports:
      - "5000:5000"
    expose:
      - "5000"
    links:
      - database

  angular_app:
    build: ./front-prepagas
    container_name: angular_app
    ports:
      - 4200:80
  

  # nginx:
  #   build: ./nginx
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #   links:
  #     - express_app
  #     - angular_app
