name: publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_DEPLOY }}

      - name: Build and push image
         run: |
          docker-compose up . --tag ghcr.io/hernanpsc/mean:latest
          docker push . --tag ghcr.io/hernanpsc/mean:latest


  # deploy:
  #   needs: create-docker-image
  #   runs.on: ubuntu-latest
  #   steps:
  #     - name: Install sshpass
  #       run: sudo apt-get inatall -y sshpass

  #     - name: SSH into Server
  #       run: |
  #         sshpadd -p ${{ secrets.AUTH_PASS }} ssh -o StrictHostKeyChecking=no $ {{ secrets.AUTH_SERVER }}


        